Repository canonical/charmed-openstack-upgrader, pull requests merged in 2023-10, with the labels that each got.

#111 drop parallel for `cou plan`
  completions/bash/cou_bash_completion
  cou/commands.py
  tests/unit/test_commands.py
Labels: bug

#102 using new v2 branch for CI testing
  .github/workflows/check.yaml
  .github/workflows/sonar.yaml
Labels: enhancement

#114 introduce cancel to `UpgradeStep`
  cou/apps/auxiliary.py
  cou/apps/core.py
  cou/exceptions.py
  cou/steps/__init__.py
  cou/steps/plan.py
  cou/utils/juju_utils.py
  pyproject.toml
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_execute.py
  tests/unit/steps/test_steps.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_cli.py
Labels: bug, enhancement

#112 add catch for TimeoutException
  cou/cli.py
  cou/utils/juju_utils.py
  tests/unit/test_cli.py
  tests/unit/utils/test_juju_utils.py
Labels: bug

#113 waiting for model or application to be idle
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/apps/core.py
  cou/apps/factory.py
  cou/apps/subordinate.py
  cou/steps/analyze.py
  cou/steps/plan.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_core.py
  tests/unit/conftest.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/steps/test_steps_plan.py
Labels: bug

#137 Check if application can upgrade to the current channel
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/base.py
  cou/apps/subordinate.py
  cou/steps/__init__.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/steps/test_steps.py
Labels: medium

#125 Move channel getter/setter to OpenStack and Auxiliary Applications
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/apps/subordinate.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
Labels: high

#130 Remove setting require_osd_release in post_upgrade step of ceph-mon
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/cli.py
  cou/utils/app_utils.py
  cou/utils/juju_utils.py
  cou/utils/openstack.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/test_cli.py
  tests/unit/utils/test_app_utils.py
  tests/unit/utils/test_juju_utils.py
Labels: high
