Repository canonical/charmed-openstack-upgrader, pull requests merged in 2023-11, with the labels that each got.

#156 Channel Based Class to support gnocchi, designate-bind and glance-simplestreams
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/steps/plan.py
  cou/utils/openstack.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/conftest.py
Labels: bug, high

#134 Improve handling of Ubuntu series and OS release combinations
  cou/cli.py
  cou/exceptions.py
  cou/steps/analyze.py
  cou/steps/plan.py
  cou/utils/openstack.py
  tests/unit/conftest.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_cli.py
Labels: enhancement, low

#157 clean up usage of environment variables
  README.md
  cou/commands.py
  cou/logging.py
  cou/steps/backup.py
  cou/utils/__init__.py
Labels: bug, low

#159 Make backup step optional with CLI parameter
  completions/bash/cou_bash_completion
  cou/cli.py
  cou/commands.py
  cou/steps/plan.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_cli.py
  tests/unit/test_commands.py
Labels: enhancement, low

#160 increase waiting time
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/apps/core.py
  cou/steps/plan.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_steps_plan.py
Labels: bug, high

#168 Wait only for apps related with COU
  cou/utils/juju_utils.py
  tests/unit/utils/test_juju_utils.py
Labels: bug, high

#109 catch KeyboardInterrupt error
  cou/__main__.py
  cou/cli.py
  cou/exceptions.py
  cou/steps/__init__.py
  cou/steps/execute.py
  cou/utils/__init__.py
  cou/utils/cli.py
  tests/unit/steps/test_steps.py
  tests/unit/test_cli.py
  tests/unit/test_main.py
  tests/unit/utils/test_cli.py
Labels: bug, high

#163 Create separate classes for different types of steps
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/apps/subordinate.py
  cou/cli.py
  cou/exceptions.py
  cou/steps/__init__.py
  cou/steps/execute.py
  cou/steps/plan.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/apps/utils.py
  tests/unit/steps/test_steps.py
  tests/unit/steps/test_steps_execute.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_cli.py
Labels: high

#170 Remove COU_DATA env var
  README.md
  bin/cou.wrapper
  cou/utils/__init__.py
  tests/functional/tests/backup.py
  tests/unit/conftest.py
  tox.ini
Labels: bug, medium

#172 Add wait for related apps as pre-upgrade
  cou/steps/plan.py
  tests/unit/steps/test_steps_plan.py
Labels: bug, medium

#171 using current model if no model_name provided
  cou/cli.py
  cou/utils/juju_utils.py
  tests/functional/tests/backup.py
  tests/unit/test_cli.py
  tests/unit/utils/test_juju_utils.py
Labels: bug, medium

#175 Add idle_period as argument for wait_for_idle
  cou/apps/base.py
  cou/steps/plan.py
  cou/utils/juju_utils.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_steps_plan.py
Labels: bug, high
