Repository canonical/charmed-openstack-upgrader, pull requests merged in 2024-05, with the labels that each got.

#394 Add execution time of Applications and Hypervisors AZs
  cou/steps/execute.py
  cou/steps/hypervisor.py
  tests/mocked_plans/sample_plans/018346c5-f95c-46df-a34e-9a78bdec0018.yaml
  tests/mocked_plans/sample_plans/9eb9af6a-b919-4cf9-8f2f-9df16a1556be.yaml
  tests/mocked_plans/sample_plans/base.yaml
  tests/unit/steps/test_execute.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_plan.py
Labels: enhancement, low

#402 Add new release and promote workflow
  .github/workflows/promote.yaml
  .github/workflows/release.yaml
Labels: enhancement

#409 fix linting issue with new flake8 version
  tests/unit/steps/test_hypervisor.py
Labels: bug

#410 Add support for Juju 3.4
  .github/workflows/check.yaml
  cou/exceptions.py
  cou/steps/backup.py
  cou/utils/app_utils.py
  cou/utils/juju_utils.py
  setup.cfg
  tests/functional/tests/model.py
  tests/unit/jujustatus.json
  tests/unit/steps/test_backup.py
  tests/unit/utils/test_app_utils.py
  tests/unit/utils/test_juju_utils.py
  tests/unit/utils/test_nova_compute.py
Labels: enhancement

#422 Fetch all commits and tags in release
  .github/workflows/release.yaml
Labels: bug

#421 Use gather to improve performance of wait_for_idle
  cou/utils/juju_utils.py
  tests/unit/utils/test_juju_utils.py
Labels: bug

#424 Fix ActionFailed creating error message
  cou/exceptions.py
  cou/utils/juju_utils.py
  tests/unit/test_exceptions.py
Labels: bug
