Repository canonical/charmed-openstack-upgrader, pull requests merged in 2024-04, with the labels that each got.

#353 Fix missing machines for subordinate applications
  cou/utils/juju_utils.py
  tests/unit/utils/test_juju_utils.py
Labels: bug, high

#334 Add base structure for testing of statuses from real cloud
  .github/workflows/check.yaml
  cou/utils/nova_compute.py
  pyproject.toml
  tests/mocked_plans/conftest.py
  tests/mocked_plans/sample_plans/base.yaml
  tests/mocked_plans/test_base_plan.py
  tests/mocked_plans/utils.py
  tests/unit/conftest.py
  tests/unit/utils.py
  tox.ini
Labels: enhancement

#347 Add support for latest/stable
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/apps/subordinate.py
  tests/mocked_plans/sample_plans/base.yaml
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_plan.py
Labels: enhancement

#358 Move _verify_channel to sanity checks
  cou/apps/base.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_subordinate.py
Labels: bug, high

#359 Support OVN apps that don't have "enable-versiong-pinning" config
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/steps/plan.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/steps/test_plan.py
Labels: bug, high

#366 Add `CONTRIBUTING.md`
  CONTRIBUTING.md
  docs/index.rst
Labels: documentation

#364 Consider applications without origin setting to sanity checks
  cou/apps/base.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
Labels: bug, high

#360 Run sanity checks in HypervisorUpgradePlanner
  cou/steps/hypervisor.py
  tests/unit/steps/test_hypervisor.py
Labels: bug, medium

#378 Fix set_action_managed_upgrade
  cou/apps/base.py
  tests/mocked_plans/sample_plans/base.yaml
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_plan.py
Labels: bug, high

#372 Fix support for latest/stable for channel based apps
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/apps/subordinate.py
  cou/steps/analyze.py
  cou/steps/plan.py
  cou/utils/app_utils.py
  cou/utils/juju_utils.py
  cou/utils/nova_compute.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_analyze.py
  tests/unit/utils/test_juju_utils.py
  tests/unit/utils/test_nova_compute.py
Labels: bug, high

#379 Fix Hypervisor Upgrade
  cou/steps/__init__.py
  docs/explanation/planning.rst
  docs/reference/known-issues.rst
  tests/functional/tests/smoke.py
  tests/mocked_plans/sample_plans/base.yaml
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_execute.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_plan.py
Labels: bug, high

#385 Run update-status hook before checking workload version upgrade
  cou/apps/base.py
  tests/unit/apps/test_core.py
Labels: bug, medium
