Repository canonical/charmed-openstack-upgrader, pull requests merged in 2024-03, with the labels that each got.

#251 Add pre- and post-upgrade steps to `HypervisorUpgradePlanner`
  cou/steps/hypervisor.py
  tests/unit/steps/test_hypervisor.py
Labels: enhancement

#263 Add Cinder OpenStackApplication
  cou/apps/base.py
  cou/apps/core.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_hypervisor.py
Labels: bug

#272 Aligning name of applications
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/channel_based.py
  cou/apps/subordinate.py
  cou/steps/plan.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_steps_plan.py
Labels: enhancement

#261 Add check for enable-auto-restarts config option
  cou/apps/base.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
Labels: enhancement

#255 Separate control-plane and data-plane plans
  cou/commands.py
  cou/steps/plan.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_commands.py
Labels: enhancement

#277 Revert "fix zaza.model.run_on_unit"
  tests/functional/tests/model.py
Labels: enhancement

#275 Add cache property for applications to COUModel
  cou/utils/juju_utils.py
  tests/unit/utils/test_juju_utils.py
Labels: enhancement

#274 Moved MismatchedOpenStackVersions to Application
  cou/apps/base.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_steps_plan.py
Labels: enhancement

#283 fix issue found by new version of mypy
  cou/utils/cli.py
Labels: bug

#279 Add post-upgrade steps for whole upgrade plan
  cou/apps/auxiliary.py
  cou/steps/__init__.py
  cou/steps/plan.py
  cou/utils/app_utils.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/steps/test_steps.py
  tests/unit/steps/test_steps_plan.py
Labels: enhancement

#290 fix issue found by new version of mypy
  cou/utils/cli.py
Labels: bug

#280 Add pre-upgrade step to verify nova-compute
  cou/apps/auxiliary.py
  cou/utils/juju_utils.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/utils.py
Labels: enhancement

#287 Fix comparing of coroutines in BaseStep
  cou/steps/__init__.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_steps.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/utils.py
Labels: bug

#291 Preparation for OS app being frozen
  cou/apps/base.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
Labels: enhancement

#301 add global and func test concurrency
  .github/workflows/check.yaml
Labels: bug

#292 Add add_steps function to BaseStep
  cou/apps/base.py
  cou/steps/__init__.py
  tests/unit/steps/test_steps.py
Labels: enhancement

#308 update codeowners to soleng
  .github/CODEOWNERS
Labels: bug

#309 update codeowners to soleng
  .github/CODEOWNERS
Labels: bug

#307 Fix rich operators on OpenStackRelease
  cou/utils/openstack.py
Labels: bug, high

#305 Properly wrapping help messages
  cou/commands.py
Labels: high

#293 Add env for idle timeout
  README.md
  cou/apps/auxiliary.py
  cou/apps/base.py
  cou/apps/core.py
  docs/how-to/different-model.rst
  docs/reference/environment-variables.rst
Labels: enhancement, high

#294 Aligning OS application names
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/channel_based.py
  cou/apps/subordinate.py
  cou/steps/plan.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_subordinate.py
  tests/unit/conftest.py
Labels: enhancement

#295 Add custom namespace for CLI arguments.
  cou/cli.py
  cou/commands.py
  cou/steps/plan.py
  tests/unit/conftest.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_cli.py
  tests/unit/test_commands.py
Labels: enhancement

#296 Add dependent option to BaseStep
  cou/steps/__init__.py
  tests/unit/steps/test_steps.py
Labels: enhancement

#297 Data-plane handle already upgraded units
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/steps/hypervisor.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/steps/test_hypervisor.py
Labels: enhancement

#298 Introducing Machine for OpenStackApplication
  cou/apps/base.py
  cou/apps/factory.py
  cou/steps/analyze.py
  cou/utils/juju_utils.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_factory.py
  tests/unit/apps/test_subordinate.py
  tests/unit/conftest.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/utils/test_juju_utils.py
Labels: enhancement

#306 Generate upgrade plan for ceph-osd, principals and data-plane subordinates
  cou/steps/plan.py
  tests/unit/steps/test_steps_plan.py
Labels: enhancement

#304 Add sanity checks to app generate upgrade plan
  cou/apps/base.py
  cou/apps/subordinate.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
Labels: enhancement, high

#318 rename COUModel to Model
  cou/apps/base.py
  cou/apps/factory.py
  cou/cli.py
  cou/steps/analyze.py
  cou/steps/backup.py
  cou/utils/app_utils.py
  cou/utils/juju_utils.py
  docs/.custom_wordlist.txt
  docs/how-to/configure-connection.rst
  tests/functional/tests/backup.py
  tests/functional/tests/model.py
  tests/functional/tests/tests.yaml
  tests/unit/conftest.py
  tests/unit/test_cli.py
  tests/unit/utils/test_juju_utils.py
Labels: enhancement

#319 Cleanup unittests
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/apps/utils.py
  tests/unit/steps/test_analyze.py
  tests/unit/steps/test_backup.py
  tests/unit/steps/test_execute.py
  tests/unit/steps/test_plan.py
  tests/unit/utils.py
Labels: enhancement

#320 Add function to set action-managed-upgrade
  cou/apps/base.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/conftest.py
  tests/unit/steps/test_plan.py
  tests/unit/utils.py
Labels: enhancement

#324 Add Unit, Application and use them as base for OpenStackApplication object
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/apps/factory.py
  cou/apps/subordinate.py
  cou/steps/analyze.py
  cou/utils/juju_utils.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_factory.py
  tests/unit/apps/test_subordinate.py
  tests/unit/conftest.py
  tests/unit/steps/test_analyze.py
  tests/unit/steps/test_plan.py
  tests/unit/utils.py
  tests/unit/utils/test_juju_utils.py
Labels: enhancement

#323 Add explanation for different upgrade strategies
  docs/.custom_wordlist.txt
  docs/explanation/upgrade.rst
Labels: documentation

#322 Update How-to guides for plan and upgrade.
  docs/.custom_wordlist.txt
  docs/how-to/plan-upgrade.rst
  docs/how-to/upgrade-cloud.rst
Labels: documentation

#316 Add logic for step to raise HaltUpgradeExecution
  cou/exceptions.py
  cou/steps/execute.py
  tests/unit/steps/test_execute.py
Labels: enhancement

#328 Merging the dev/data-plane to main
  .github/workflows/check.yaml
  completions/bash/cou_bash_completion
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/apps/core.py
  cou/apps/subordinate.py
  cou/cli.py
  cou/commands.py
  cou/exceptions.py
  cou/steps/__init__.py
  cou/steps/analyze.py
  cou/steps/hypervisor.py
  cou/steps/plan.py
  cou/utils/nova_compute.py
  docs/how-to/interruption.rst
  docs/how-to/no-backup.rst
  docs/how-to/plan-upgrade.rst
  docs/how-to/upgrade-cloud.rst
  pyproject.toml
  setup.cfg
  tests/functional/tests/smoke.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_plan.py
  tests/unit/test_cli.py
  tests/unit/test_commands.py
  tests/unit/utils/test_juju_utils.py
  tests/unit/utils/test_nova_compute.py
Labels: enhancement, high

#341 Fix apps split between control-plane and data-plane
  cou/steps/analyze.py
  tests/unit/steps/test_analyze.py
Labels: bug, high

#331 Add `_check_ovn_support` for `ovn-chassis`, `ovn-central` and `ovn-dedicated-chassis`
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
Labels: bug

#342 Verify Hypervisors CLI input just for hypervisors machines
  cou/steps/plan.py
  tests/unit/steps/test_plan.py
Labels: bug

#337 Fix enable and disable scheduler order on upgrade
  cou/apps/core.py
  cou/steps/hypervisor.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_plan.py
Labels: bug
