Repository canonical/charmed-openstack-upgrader, pull requests merged in 2024-02, with the labels that each got.

#230 Refactor/bseng 1938/froze openstackapplication prep
  cou/apps/base.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/conftest.py
Labels: enhancement

#227 Add base architecture of HypervisorUpgradePlanner
  cou/steps/__init__.py
  cou/steps/hypervisor.py
  pyproject.toml
  tests/unit/steps/test_steps.py
Labels: enhancement

#240 Introduced COUApplication, COUUnit and COUMachine
  cou/apps/base.py
  cou/apps/factory.py
  cou/apps/machine.py
  cou/steps/analyze.py
  cou/steps/plan.py
  cou/utils/juju_utils.py
  cou/utils/nova_compute.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_machines.py
  tests/unit/conftest.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/utils/test_juju_utils.py
Labels: enhancement

#242 feature: using COUApplication as base for OpenStackApplication
  cou/apps/auxiliary.py
  cou/apps/auxiliary_subordinate.py
  cou/apps/base.py
  cou/apps/channel_based.py
  cou/apps/factory.py
  cou/steps/analyze.py
  cou/steps/hypervisor.py
  cou/steps/plan.py
  cou/utils/nova_compute.py
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_factory.py
  tests/unit/apps/test_subordinate.py
  tests/unit/conftest.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/utils.py
  tests/unit/utils/test_nova_compute.py
Labels: enhancement

#244 use self-hosted runner and LXD cloud for CI
  .github/workflows/check.yaml
Labels: bug, enhancement

#250 fix can_upgrade_to field
  tests/unit/apps/test_auxiliary.py
  tests/unit/apps/test_auxiliary_subordinate.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_channel_based.py
  tests/unit/apps/test_core.py
  tests/unit/apps/test_subordinate.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/steps/test_steps_plan.py
Labels: bug

#246 Implement AZ grouping mechanism
  cou/apps/base.py
  cou/steps/hypervisor.py
  tests/unit/apps/test_base.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/utils/test_nova_compute.py
Labels: enhancement

#252 drop `--hostname` from CLI
  cou/commands.py
  cou/steps/plan.py
  cou/utils/juju_utils.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_steps_analyze.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_commands.py
  tests/unit/utils/test_juju_utils.py
  tests/unit/utils/test_nova_compute.py
Labels: bug, enhancement

#257 fix zaza.model.run_on_unit
  tests/functional/tests/model.py
Labels: bug

#248 Add tuple of apps to COUMachine
  cou/utils/juju_utils.py
  tests/functional/tests/model.py
  tests/unit/steps/test_hypervisor.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/utils/test_juju_utils.py
Labels: enhancement

#259 remove message to manually upgrade data-plane
  cou/cli.py
  cou/steps/plan.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_cli.py
Labels: bug

#262 Add specific test for NovaCompute upgrade plan
  cou/apps/core.py
  tests/unit/apps/test_core.py
  tests/unit/utils.py
Labels: bug

#254 Add hypervisors option to CLI
  cou/commands.py
  cou/steps/plan.py
  tests/unit/steps/test_steps_plan.py
  tests/unit/test_commands.py
Labels: enhancement

#264 Improve 'action-managed-upgrade' config handling
  cou/apps/base.py
  tests/unit/apps/test_base.py
  tests/unit/apps/test_core.py
  tests/unit/steps/test_steps_plan.py
Labels: bug

#260 Skip to add an empty step
  cou/apps/base.py
  cou/steps/__init__.py
  tests/unit/steps/test_steps.py
Labels: enhancement
